
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umeshdb
    username: root
    password: drowssap
    jpa.properties.hibernate.dialect:  org.hibernate.dialect.MySQL5Dialect


flyway:
  validate-on-migrate: false
  encoding: UTF-8
  out-of-order: true